nginx-proxy:
  image: jwilder/nginx-proxy
  restart: allways
  ports:
    -  "80:80"
  volumes: 
    -  /var/run/docker.sock:/tmp/docker.sock:ro
www:
  image: nginx
  restart: always
  expose:
   - "80"
  volumes: 
   - /var/ajed/www:/usr/share/nginx/html:ro
  environment:
   - VIRTUAL_HOST=arnaldoespinoza.com,www.arnaldoespinoza.com